# Generated by Django 4.2.5 on 2023-10-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_delete_choice_delete_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mychoice",
            old_name="choice_text",
            new_name="mychoice_text",
        ),
    ]
